version: '3.8'

services:
  # The Source: Farm Management System
  farm_pg_source:
    image: postgres:15
    environment:
      - POSTGRES_USER=farm_admin
      - POSTGRES_PASSWORD=farm_password
      - POSTGRES_DB=farm_management
    ports:
      - "5434:5432"
    volumes:
      - farm_pg_data:/var/lib/postgresql/data
    networks:
      - data_network

  # Database UI for easy querying
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@farm.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - farm_pg_source
    networks:
      - data_network

  # Local Data Lake (Replaces GCS / AWS S3)
  minio:
    image: minio/minio:latest
    container_name: local_minio
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data_network

  # Orchestrator
  kestra:
    image: kestra/kestra:latest
    command: server local
    ports:
      - "8082:8080"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../ingestion:/app/ingestion
      - ../warehouse:/app/warehouse
    networks:
      - data_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
      image: confluentinc/cp-kafka:7.5.0
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        # Add this line so Kafka listens for both Kestra/Spark and your laptop
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  farm_pg_data:
    name: docker_farm_pg_data
  minio_data:

networks:
  data_network:
    driver: bridge